project_id = "gpprdjdeydavukbufibf"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-chat-notification]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false

[functions.create-checkout-session]
enabled = true
verify_jwt = true
import_map = "./functions/create-checkout-session/deno.json"
entrypoint = "./functions/create-checkout-session/index.ts"

[functions.webhook-stripe]
enabled = true
verify_jwt = false
