project_id = "gpprdjdeydavukbufibf"

[functions.send-booking-notification]
verify_jwt = false

[functions.send-chat-notification]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.verify-checkout]
verify_jwt = false

[functions.verify-stripe-session]
verify_jwt = false

[functions.complete-account-setup]
verify_jwt = false

[functions.webhook-stripe]
verify_jwt = false
