project_id = "gpprdjdeydavukbufibf"

[functions.chat]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.send-chat-notification]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false